### ISSUE TITLE
compatibility with latest pegjs

### ISSUE THREAD

**Issue by gitshub** [dbalcomb/pegjs-require#2]
```
Hi,
```

   Have you tested your module with the latest version of pegjs?

```
Apparently your latest version is

    pegjs-require 1.0.0

    @dbalcomb dbalcomb released this on Jan 25

and the latest release of pegjs is

    0.10.0

    Released: August 19, 2016


I am a novice at Javascript and Node, so this may be my fault,but when I try to follow your example...

"And then require any PEG.js grammar:

var parser = require('./grammar.pegjs');"
```

...with my grammar, I get

```
TypeError: Object #<Object> has no method 'buildParser'
    at Object.require.extensions..pegjs        (/home/owner1/Downloads/node_modules/pegjs-require/index.js:13:19)
```

Perhaps this is because of API changes.  The pegjs Change Log at
    https://github.com/pegjs/pegjs/blob/master/CHANGELOG.md
says
    API polishing. The peg.buildParser function was renamed to peg.generate.

Thank you.

**Comment by dbalcomb** [comment]
Thanks for the notification. I have just released 2.0.0 to address the issue. I was unsure about the major version bump but I thought it best as it passes through the updated PEG.js module which does have a major API change.
